apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-pvc
  namespace: {{ .Values.fastapi.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.reports.storage }}
